"""
Generate docs/api/endpoints.md from the application's OpenAPI schema.

    python tools/generate_api_reference.py          # rewrite the file
    python tools/generate_api_reference.py --check  # exit 1 if it is stale

The unit tests run the check, so the endpoint list cannot drift from the
code (issue #78). The interactive reference is served at /docs and /redoc.
"""
import os
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "api" / "endpoints.md"

HEADER = """# API endpoints

<!-- Generated by tools/generate_api_reference.py from the OpenAPI schema. Do not edit. -->

Every endpoint of the ELIES API, grouped by tag. Request and response
schemas are in the interactive reference served by the API at `/docs`
(Swagger UI) and `/redoc`; [API_REFERENCE.md](https://github.com/researchintegrity/elies/blob/main/API_REFERENCE.md)
explains authentication, conventions and the main workflows.

- **Auth**: `bearer` needs `Authorization: Bearer <token>`; `admin` also needs
  the admin role; `-` is public.
- **Deprecated** endpoints still work but will be removed; use the
  replacement named in their description.
"""


def _first_sentence(text: str) -> str:
    """First sentence of the first paragraph of a docstring, on one line."""
    paragraph = []
    for line in (text or "").strip().splitlines():
        if not line.strip():
            if paragraph:
                break
            continue
        paragraph.append(line.strip())
    sentence = " ".join(paragraph)
    end = sentence.find(". ")
    if end != -1:
        sentence = sentence[:end + 1]
    return sentence.replace("|", "\\|")


def render(schema: dict) -> str:
    by_tag = defaultdict(list)
    for path, operations in schema["paths"].items():
        for method, op in operations.items():
            tag = (op.get("tags") or ["General"])[0]
            by_tag[tag].append((path, method.upper(), op))

    out = [HEADER]
    for tag in sorted(by_tag, key=str.lower):
        out.append(f"\n## {tag}\n\n| Method | Path | Auth | Description |\n|---|---|---|---|")
        for path, method, op in sorted(by_tag[tag], key=lambda e: (e[0], e[1])):
            auth = "-"
            if op.get("security"):
                auth = "admin" if path.startswith("/admin") else "bearer"
            description = _first_sentence(op.get("description")) or op.get("summary", "")
            if op.get("deprecated"):
                description = f"**Deprecated.** {description}"
            out.append(f"| {method} | `{path}` | {auth} | {description} |")
    return "\n".join(out) + "\n"


def build_schema() -> dict:
    # Import-time settings need these; no service is contacted.
    os.environ.setdefault("JWT_SECRET", "docs-generation-only-0123456789abcdef0123456789")
    os.environ.setdefault("HOST_WORKSPACE_PATH", "/tmp/elies-docs-workspace")
    os.environ.setdefault("CONTAINER_WORKSPACE_PATH", "/tmp/elies-docs-workspace")
    sys.path.insert(0, str(ROOT))
    from app.main import app

    return app.openapi()


def main(argv) -> int:
    content = render(build_schema())
    if "--check" in argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date: run python tools/generate_api_reference.py")
            return 1
        return 0
    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
